### ISSUE TITLE
Posts not accessible anymore

### ISSUE THREAD

**Issue by XSven** [kadler/kadler.github.io#9]
Recently I have detected that some of your posts are not accessible anymore (401 There isn't a GitHub Pages site here.)

Not accessible
https://kadler.io/2017/09/08/libpath.html
https://kadler.io/2017/11/17/how-to-libpath.html

Accessible
https://kadler.github.io/2017/09/01/path.html

**Comment by kadler** [comment]
It keeps unsetting my custom domain for whatever reason :angry: The standard github.io link should always work.

**Comment by kadler** [comment]
Fixed by https://github.com/kadler/kadler.github.io/commit/fcb596489cf516499716fe4983d8880ddc46fa16
